apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc-toobig
  namespace: test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: ""