apiVersion: v1
kind: Service
metadata:
  name: lab-numbers-web-v2
  namespace: test
spec:
  type: LoadBalancer
  selector:
    app: lab-numbers-web
    version: v2
  ports:
    - port: 8088
      targetPort: 80
