apiVersion: v1
kind: Service
metadata:
  name: todo-web
  namespace: test
spec:
  type: LoadBalancer
  selector:
    app: todo-web
  ports:
    - port: 8080
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-web
  namespace: test
spec:
  selector:
    matchLabels:
      app: todo-web
  template:
    metadata:
      labels:
        app: todo-web
    spec:
      containers:
        - name: web
          image: kiamol/ch04-todo-list
          env:
            - name: Logging__LogLevel__Default
              value: Warning