apiVersion: v1
kind: Service
metadata:
  name: pi-proxy
  namespace: test
  labels:
    app: pi-proxy
spec:
  type: LoadBalancer
  selector:
    app: pi-proxy
  ports:
    - port: 8080
      targetPort: 80