apiVersion: v1
kind: Service

metadata:
  name: numbers-web
  namespace: test

spec:
  # 외부 트래픽도 전달할 수 있는 서비스 종류
  type: LoadBalancer
  selector:
    app: numbers-web
  ports:
    # 서비스가 주시하는 포트
    # 클라이언트가 요청하는 포트 중 감지할 포트로,
    # 8088을 요청할 경우 해당 서비스가 감지하여, targetPort로 트래픽을 전달한다.
    - port: 8088
      targetPort: 80 # 트래픽이 전달될 파드의 포트