apiVersion: v1
kind: Service
metadata:
  name: adminer-web
  namespace: test
spec:
  type: LoadBalancer
  selector:
    app: adminer-web
  ports:
    - port: 8082
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer-web
  namespace: test
spec:
  selector:
    matchLabels:
      app: adminer-web
  template:
    metadata:
      labels:
        app: adminer-web
    spec:
      containers:
        - name: web
          image: adminer:4.7-standalone
          args: ["php", "-S", "0.0.0.0:8080", "-t", "/var/www/html"]
          env:
            - name: ADMINER_DEFAULT_SERVER
              valueFrom:
                secretKeyRef:
                  name: adminer-secret
                  key: defaultServerName
            - name: ADMINER_DESIGN
              valueFrom:
                configMapKeyRef:
                  name: adminer-web-config
                  key: config