apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-db
  namespace: test
spec:
  selector:
    matchLabels:
      app: todo-db
  template:
    metadata:
      labels:
        app: todo-db
    spec:
      containers:
        - name: db
          image: postgres:11.6-alpine
          env:
            - name: POSTGRES_PASSWORD_FILE
              value: /secrets/postgres_password
          volumeMounts:
            - 