apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-web-lab-pvc
  namespace: test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: ""