apiVersion: v1
kind: Service
metadata:
  name: whoami-web
  namespace: test
  labels:
    kiamol: ch06
spec:
  type: LoadBalancer
  selector:
    app: whoami-web
  ports:
    - port: 8088
      targetPort: 80